
title: Clutch.Play
description: Tactics. Insights. Esports. All in one place.
url: "https://clutchplay.online"
baseurl: ""
author: Narendra
timezone: Asia/Kolkata

remote_theme: daattali/beautiful-jekyll@master

# Navigation
navbar-links:
  Home: /
  Sports: "/sports"
  Gaming: "/gaming"
  About: "/about"

# Social Media
social-network-links:
  twitch: undercoveralchemist

# Site settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude unnecessary files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
