
title: Clutch.Play
description: Clutchplay is your ultimate destination for sports and gaming enthusiasts. Dive into in-depth tactical breakdowns and expert insights on football, cricket, chess, and tennis and other sports plus fresh coverage of new game releases and the latest in esports. Passionate analysis, winning strategies, and bold opinions—all in one clutch play.
url: "https://clutchplay.online"
baseurl: ""
author: Narendra
timezone: Asia/Kolkata

remote_theme: daattali/beautiful-jekyll@master

# Navigation
navbar-links:
  Home: /
  Sports: "/sports"
  Gaming: "/gaming"
  About: "/about"

# Social Media
social-network-links:
  twitch: undercoveralchemist

# Site settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude unnecessary files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
