---
remote_theme: daattali/beautiful-jekyll@master

title: "Clutchplay"
description: "Clutchplay is your ultimate destination for sports and gaming enthusiasts. Dive into in-depth tactical breakdowns and expert insights on football, cricket, chess, tennis, and other sports — plus fresh coverage of new game releases and the latest in esports. Passionate analysis, winning strategies, and bold opinions—all in one clutch play."

url: "https://clutchplay.online"
baseurl: ""

logo: "assets/img/clutchplay-logo.png"
avatar: "assets/img/avatar.png"

permalink: "/:year/:month/:day/:title/"
paginate: 5
disqus: "clutchplay-online"

author_name: "Narendra aka UndercoverAlchemist"
author_email: "undercoveralchemist@tuta.io"

twitch_username: "UndercoverAlchemist"
github_username: "RollingThunder"
twitter_username: "AlchemistFIFA"

custom_css: "assets/css/custom.css"

footer-links:
  email: true
  twitch: true
  twitter: true
  github: true

navigation_header: true

nav:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Blog"
    url: "/blog/"
  - title: "Analysis"
    url: "/analysis/"
  - title: "Twitch Streams"
    url: "/twitch/"
  - title: "Contact"
    url: "/contact/"
